---
title: "INLA DLNM model"
author: "Nick Davies, Simon Frost"
format: gfm
---

## Libraries

```{r}
library(INLA)
library(ggplot2)
library(dlnm)
library(data.table)
library(RColorBrewer)
library(stringr)
```

```{r}
set.seed(123)  # for reproducibility
```

## Load data and process

```{r}
df <- read.table("../data/lassa_states_endemic.tsv", header=TRUE, row.names=NULL)
# Exclude missing (forecast) datapoints
df <- df[!is.na(df$y),]
nb_loc <- "../data/states_nbmatrix"
```

### Set up cross-basis

```{r}

get_crossbasis = function(df, colstart, xknots_q, tknots_n, prefix = "v")
{
    stopifnot(length(xknots_q) > 2)
    stopifnot(tknots_n > 1)
    setDT(df)
    
    # Get lagged data; each successive column is at a longer lag time
    data = df[, .SD, .SDcols = patterns(paste0("^", colstart))]
    
    # Inner knots and boundary points
    points = quantile(data[, 1], xknots_q, na.rm = TRUE)
    boundary = c(points[1], tail(points, 1))
    knots = head(tail(points, -1), -1)
    
    # knots along time dimension: this is in units of lags, not units of
    # time per se (e.g. if lag is 0, 30, 60 then lag is ...?)
    # TODO looking at the output of logknots, I can't really make sense of it...
    tk = ncol(data)^(1/tknots_n)
    tknots = tk^(0:(tknots_n - 1))
    
    cb = crossbasis(data,
       argvar = list(fun = "ns", knots = knots, Boundary.knots = boundary),
       arglag = list(fun = "ns", knots = tknots, intercept = TRUE)
    )
    colnames(cb) = str_replace(colnames(cb), "^v", prefix)
    cb
}

cb_spi3 = get_crossbasis(df, "spi3_", c(0, 1/3, 2/3, 1), 3, "spi3_")
cb_precip = get_crossbasis(df, "precip_[0-9]+$", c(0, 1/3, 2/3, 1), 3, "precip_")
```

## Fit model

Priors.

```{r}
# fixed effects priors
control.fixed1 = list(
  mean.intercept = 0, # prior mean for intercept
  prec.intercept = 0.01, # prior precision for intercept
  mean = 0, # prior mean for fixed effects
  prec = 1,  # prior precision for (scaled) fixed effects
  correlation.matrix = TRUE # compute posterior correlation matrix
)

# hyperpriors for iid, ar1, bym2
hyper.iid = list(theta = list(prior="pc.prec", param=c(1, 0.01)))

# for bym or bym2
hyper.bym = list(theta1 = list(prior="pc.prec", param=c(1, 0.01)),
                 theta2 = list(prior="pc.prec", param=c(1, 0.01)))
hyper.bym2 = list(theta1 = list(prior="pc.prec", param=c(1, 0.01)),
                  theta2 = list(prior="pc", param=c(0.5, 0.5)))

# ar1
hyper.ar1 = list(theta1 = list(prior='pc.prec', param=c(1, 0.01)), 
                 rho = list(prior='pc.cor0', param = c(0.75, 0.5)))

# random walk hyperparameters on smoothing
hyper1.rw = list(prec = list(prior='pc.prec', param=c(0.1, 0.01))) # strictest; sd constrained to be low
hyper2.rw = list(prec = list(prior='pc.prec', param=c(0.5, 0.01))) # medium
hyper3.rw = list(prec = list(prior='pc.prec', param=c(1, 0.01))) # weakest; sd can be quite wide 
```

Define formula, using lag for `spi3` and `precip` variables.

```{r}
form = formula(y ~ 1 +
                 offset(logpop) + 
                 f(polyid, model="bym2", graph=nb_loc, scale.model=TRUE, constr=TRUE, adjust.for.con.comp=TRUE, hyper=hyper.bym2) +
                 f(year, model="rw1", replicate=polyid2, scale.model=TRUE, constr=TRUE, hyper=hyper3.rw) +
                 f(epiWeek, model="rw2", cyclic=TRUE, replicate=region2, scale.model=TRUE, constr=TRUE, hyper=hyper3.rw) +
                 # f(spi, model="rw2", scale.model=TRUE, constr=TRUE, hyper=hyper2.rw) +
                 # f(precip, model="rw2", scale.model=TRUE, constr=TRUE, hyper=hyper2.rw) +
                 cb_spi3 +
                 cb_precip)
```

```{r}
fit <- inla(form,
            verbose = FALSE,
            data = df,
            family = "nbinomial",
            control.fixed = control.fixed1, # prior precision for (scaled) fixed effects
            control.predictor=list(compute=TRUE,
                                   link=1),
            control.compute=list(cpo=TRUE,
                                 waic=TRUE,
                                 dic=TRUE,
                                 config=TRUE,
                                 return.marginals=TRUE),
            control.inla = list(strategy='adaptive', # adaptive gaussian
                                cmin=0), # fixing Q factorisation issue https://groups.google.com/g/r-inla-discussion-group/c/hDboQsJ1Mls)
            inla.mode = "experimental")

```

## Model summary

```{r}
summary(fit)
```

## Lag predictors - based on Rachel Lowe, hydromet_deng repo

```{r}
plot_lag_surface = function(model, cb, pattern, name, cen)
{
    # extract full coef and vcov and create indicators for each term
    coef <- model$summary.fixed$mean
    vcov <- model$misc$lincomb.derived.covariance.matrix
    
    # find position of the terms associated with crossbasis
    indt <- grep(pattern, model$names.fixed)

    # extract predictions from the DLNM centred on overall mean 
    predt <- crosspred(cb, coef = coef[indt], vcov = vcov[indt,indt],
                       model.link = "log", bylag = 0.25, cen = cen) 
    
    # contour plot of exposure-lag-response associations
    x <- predt$predvar
    z <- predt$matRRfit
    y <- seq(0, 180, length.out = dim(z)[2])

    pal <- rev(brewer.pal(11, "PRGn"))
    levels <- pretty(z, 20)
    col1 <- colorRampPalette(pal[1:6])
    col2 <- colorRampPalette(pal[6:11])
    cols <- c(col1(sum(levels < 1)), col2(sum(levels > 1)))

    filled.contour(x, y, z,
        xlab = name, ylab = "Lag (days)", main = "",
        col = cols, levels = levels)
}

pdf("contour2.pdf", width = 6.5, height = 5, onefile = TRUE)
plot_lag_surface(fit, cb_spi3, "^spi3", "SPI-3", cen = 0)
plot_lag_surface(fit, cb_precip, "^precip", "Precipitation (mm)", cen = 7)
dev.off()

```
