---
title: "INLA bivariate model"
author: "Simon Frost"
format: gfm
---

## Libraries

```{r}
library(INLA)
library(ggplot2)
```

```{r}
set.seed(123)  # for reproducibility
```

## Load data and process

```{r}
df <- read.table("../data/lassa_states_endemic.tsv", header=TRUE, row.names=NULL)
# Exclude missing (forecast) datapoints
df <- df[!is.na(df$y),]
nb_loc <- "../data/states_nbmatrix"
```

```{r}
vars <- c("y","ys","logpop","polyid","polyid2","region", "region2","year","epiWeek","spi","precip")
df2 <- df[,vars]
```

```{r}
df_long <- rbind(
  transform(df2, y_bi = y,  k = 1),
  transform(df2, y_bi = ys, k = 2)
)
df_long$k <- factor(df_long$k)
df_long$k2 <- as.integer(df_long$k)
```

## Fit model

Priors.

```{r}
# fixed effects priors
control.fixed1 = list(mean.intercept=0, # prior mean for intercept
                      prec.intercept=0.01, # prior precision for intercept
                      mean=0, # prior mean for fixed effects
                      prec=1)  # prior precision for (scaled) fixed effects

# hyperpriors for iid, ar1, bym2
hyper.iid = list(theta = list(prior="pc.prec", param=c(1, 0.01)))

# for bym or bym2
hyper.bym = list(theta1 = list(prior="pc.prec", param=c(1, 0.01)),
                 theta2 = list(prior="pc.prec", param=c(1, 0.01)))
hyper.bym2 = list(theta1 = list(prior="pc.prec", param=c(1, 0.01)),
                  theta2 = list(prior="pc", param=c(0.5, 0.5)))

# ar1
hyper.ar1 = list(theta1 = list(prior='pc.prec', param=c(1, 0.01)), 
                 rho = list(prior='pc.cor0', param = c(0.75, 0.5)))

# random walk hyperparameters on smoothing
hyper1.rw = list(prec = list(prior='pc.prec', param=c(0.1, 0.01))) # strictest; sd constrained to be low
hyper2.rw = list(prec = list(prior='pc.prec', param=c(0.5, 0.01))) # medium
hyper3.rw = list(prec = list(prior='pc.prec', param=c(1, 0.01))) # weakest; sd can be quite wide

# prior on correlations
control.group1 = list(model="exchangeable",hyper=list(rho=list(prior="pc.cor0", param=c(0.5,0.5))))
```

Define formula, using single `spi` and `precip` variables.

```{r}
# Outcome-specific intercepts:
# 0 + k yields two intercepts (one per outcome)
form <- formula(
  y_bi ~ 0 + k +
    offset(logpop) +
    f(polyid,  model="bym2", graph=nb_loc, scale.model=TRUE, constr=TRUE,
      adjust.for.con.comp=TRUE, hyper=hyper.bym2,
      group = k2, control.group = control.group1) +
    f(year,    model="rw1", replicate=polyid2, scale.model=TRUE, constr=TRUE, hyper=hyper3.rw,
      group = k2, control.group = control.group1) +
    f(epiWeek, model="rw2", cyclic=TRUE, replicate=region2, scale.model=TRUE, constr=TRUE, hyper=hyper3.rw,
      group = k2, control.group = control.group1) +
    f(spi,     model="rw2", scale.model=TRUE, constr=TRUE, hyper=hyper2.rw,
      group = k2, control.group = control.group1) +
    f(precip,  model="rw2", scale.model=TRUE, constr=TRUE, hyper=hyper2.rw,
      group = k2, control.group = control.group1)
)
```

```{r}
fit <- inla(form,
            verbose = FALSE,
            data = df_long,
            family = "nbinomial",
            control.family = list(hyper=list(theta=list(prior="pc.prec", param=c(1,0.01)))),  # shared dispersion
            control.fixed = control.fixed1, # prior precision for (scaled) fixed effects
            control.predictor=list(compute=TRUE,
                                   link=1),
            control.compute=list(cpo=TRUE,
                                 waic=TRUE,
                                 dic=TRUE,
                                 config=TRUE,
                                 return.marginals=TRUE),
            control.inla = list(strategy='adaptive', # adaptive gaussian
                                cmin=0), # fixing Q factorisation issue https://groups.google.com/g/r-inla-discussion-group/c/hDboQsJ1Mls)
            inla.mode = "experimental")
```



## Model summary

```{r}
summary(fit)
```
